#数据库
database:
  #是否使用MySQL(true为MySQL, false为SQLite)
  enableMySQL: false
  #数据库名(MySQL与SQLite通用)
  dataBaseName: mailbox
  #数据表前缀(MySQL与SQLite通用)
  dataTablePrefix: mailbox
  #MySQL数据库地址(仅MySQL)
  mySQLhost: localhost
  #MySQL数据库端口(仅MySQL)
  mySQLport: 3306
  #MySQL数据库用户名(仅MySQL)
  mySQLusername: 'root'
  #MySQL数据库密码(仅MySQL)
  mySQLpassword: '111aaa'
#插件配置
mailbox:
  #启动服务器时进行更新检查
  updateCheck: true
  #插件提示信息前缀(设置为 无 则不显示)
  prefix: [邮箱]
  #普通 插件信息颜色
  normalMessage: §6
  #成功 插件信息颜色
  successMessage: §a
  #失败 插件信息颜色
  warningMessage: §c
  #邮件类型显示名称
  name:
    #system 类型邮件
    system: '[系统邮件]'
    #player 类型邮件
    player: '[玩家邮件]'
    #permission 类型邮件
    permission: '[权限邮件]'
  #player邮件过期时间
  player_maxtime: 30
  #player类型邮件上限可选择数量
  #填好数组并给玩家对应权限
  #权限判定顺序从上到下
  player_max: 
    #发件上限
    #mailbox.send.player.out.x
    out: 
    - 10
    - 5
    - 2
  #附件
  file:
    #指令分隔符
    divide: '.'
    #指令
    command:
      #领取邮件的玩家变量
      player: '%player%'
  #Vault经济插件
  vault:
    #显示名称
    display: '§e金币'
    #玩家单封邮件可发送的最大数量
    max: 5000
  #PlayerPoints点券插件
  player_points:
    #显示名称
    display: '§b点券'
    #玩家单封邮件可发送的最大数量
    max: 5000