package com.tripleying.qwq.MailBox.VexView;

import com.tripleying.qwq.MailBox.API.MailBoxAPI;
import com.tripleying.qwq.MailBox.ConfigMessage;
import com.tripleying.qwq.MailBox.Events.DoubleKeyPress;
import com.tripleying.qwq.MailBox.Events.JoinAndQuit;
import com.tripleying.qwq.MailBox.Events.SingleKeyPress;
import com.tripleying.qwq.MailBox.Events.VexGuiOpen;
import com.tripleying.qwq.MailBox.MailBox;
import java.io.File;
import java.util.List;
import lk.vexview.gui.components.HoverTextComponent;
import lk.vexview.gui.components.VexHoverText;
import org.bukkit.Bukkit;
import org.bukkit.configuration.file.YamlConfiguration;

public class VexViewConfig {
        
    private static final String DATA_FOLDER = "plugins/MailBox/VexView";
    private static final String JAR_FOLDER = "com/tripleying/qwq/MailBox/VexView/Default/";
    
    // 配置VexView
    public static void VexViewConfigSet(){
        Bukkit.getConsoleSender().sendMessage(ConfigMessage.vexview);
        Bukkit.getPluginManager().registerEvents(new VexGuiOpen(), MailBox.getInstance());
        VexViewConfig config = new VexViewConfig();
        config.ConfigExist();
        config.ConfigLoad();
    }
    
    public void ConfigSet(YamlConfiguration hud, 
            YamlConfiguration box, 
            YamlConfiguration content, 
            YamlConfiguration select, 
            YamlConfiguration send, 
            YamlConfiguration item_modify, 
            YamlConfiguration item_list, 
            YamlConfiguration cdkey){
        // 配置常驻Hud
        if(hud.getBoolean("hud.enable")){
            MailBoxHud.setHudConfig(
                hud.getString("hud.id"),
                hud.getString("hud.img"),
                hud.getInt("hud.x"),
                hud.getInt("hud.y"),
                hud.getInt("hud.w"),
                hud.getInt("hud.h"),
                hud.getInt("hud.ww"),
                hud.getInt("hud.hh")
            );
            Bukkit.getPluginManager().registerEvents(new JoinAndQuit(true, true), MailBox.getInstance());
        }else{
            Bukkit.getPluginManager().registerEvents(new JoinAndQuit(true, false), MailBox.getInstance());
        }
        // 配置邮件提醒Hud
        MailTipsHud.setHudConfig(
            hud.getString("new.id"),
            hud.getString("new.img"),
            hud.getInt("new.x"),
            hud.getInt("new.y"),
            hud.getInt("new.w"),
            hud.getInt("new.h"),
            hud.getInt("new.ww"),
            hud.getInt("new.hh"),
            hud.getInt("new.time")
        );
        // 配置BoxGui
        MailBox.getInstance().setOpenCmd(box.getBoolean("gui.openCmd"));
        String key = box.getString("gui.openKey");
        if(!key.equals("0")){
            if(key.contains("+")){
                int l = key.indexOf("+");
                String key1 = key.substring(0, l);
                String key2 = key.substring(l+1);
                Bukkit.getPluginManager().registerEvents(new DoubleKeyPress(Integer.parseInt(key1), Integer.parseInt(key2)), MailBox.getInstance());
                Bukkit.getConsoleSender().sendMessage(ConfigMessage.double_box);
            }else{
                Bukkit.getPluginManager().registerEvents(new SingleKeyPress(Integer.parseInt(key)), MailBox.getInstance());
                Bukkit.getConsoleSender().sendMessage(ConfigMessage.single_box);
            }
        }
        MailBoxGui.setBoxConfig(
            box.getString("gui.img"),
            box.getInt("gui.x"),
            box.getInt("gui.y"),
            box.getInt("gui.w"),
            box.getInt("gui.h"),
            box.getInt("gui.ww"),
            box.getInt("gui.hh"),
            box.getString("button.new.id"),
            box.getString("button.new.text"),
            box.getStringList("button.new.hover"),
            box.getString("button.new.img_1"),
            box.getString("button.new.img_2"),
            box.getInt("button.new.x"),
            box.getInt("button.new.y"),
            box.getInt("button.new.w"),
            box.getInt("button.new.h"),
            box.getString("button.box.id"),
            box.getString("button.box.text_r"),
            box.getString("button.box.text_s"),
            box.getString("button.box.img_1"),
            box.getString("button.box.img_2"),
            box.getInt("button.box.x"),
            box.getInt("button.box.y"),
            box.getInt("button.box.w"),
            box.getInt("button.box.h"),
            box.getString("button.cdkey.id"),
            box.getString("button.cdkey.text"),
            box.getString("button.cdkey.img_1"),
            box.getString("button.cdkey.img_2"),
            box.getInt("button.cdkey.x"),
            box.getInt("button.cdkey.y"),
            box.getInt("button.cdkey.w"),
            box.getInt("button.cdkey.h"),
            box.getString("button.onekey.id"),
            box.getString("button.onekey.text"),
            box.getStringList("button.onekey.hover"),
            box.getString("button.onekey.img_1"),
            box.getString("button.onekey.img_2"),
            box.getInt("button.onekey.x"),
            box.getInt("button.onekey.y"),
            box.getInt("button.onekey.w"),
            box.getInt("button.onekey.h"),
            box.getBoolean("title.enable"),
            box.getString("title.type"),
            box.getInt("title.x"),
            box.getInt("title.y"),
            box.getString("title.text"),
            box.getDouble("title.size"),
            box.getString("title.image"),
            box.getInt("title.w"),
            box.getInt("title.h"),
            box.getInt("list.x"),
            box.getInt("list.y"),
            box.getInt("list.w"),
            box.getInt("list.h"),
            box.getInt("list.mh"),
            box.getInt("list.sh"),
            box.getInt("list.oh"),
            box.getString("list.nullBox"),
            box.getInt("mail.oy"),
            box.getString("mail.button.id"),
            box.getString("mail.button.image_1"),
            box.getString("mail.button.image_2"),
            box.getInt("mail.button.x"),
            box.getInt("mail.button.fy"),
            box.getInt("mail.button.w"),
            box.getInt("mail.button.h"),
            box.getInt("mail.topic.x"),
            box.getInt("mail.topic.fy"),
            box.getDouble("mail.topic.size"),
            box.getString("mail.topic.noRead"),
            box.getString("mail.topic.noFile"),
            box.getInt("mail.topic.div"),
            box.getInt("mail.date.x"),
            box.getInt("mail.date.fy"),
            box.getDouble("mail.date.size"),
            box.getString("mail.date.prefix"),
            box.getStringList("mail.date.display"),
            box.getInt("mail.sender.x"),
            box.getInt("mail.sender.fy"),
            box.getDouble("mail.sender.size"),
            box.getString("mail.sender.prefix"),
            box.getStringList("mail.sender.display"),
            box.getInt("mail.type.x"),
            box.getInt("mail.type.fy"),
            box.getDouble("mail.type.size"),
            box.getString("mail.type.prefix"),
            box.getStringList("mail.type.display"),
            box.getString("mail.icon.image"),
            box.getInt("mail.icon.x"),
            box.getInt("mail.icon.fy"),
            box.getInt("mail.icon.w"),
            box.getInt("mail.icon.h"),
            box.getStringList("mail.icon.display")
        );
        // 配置ContentGui
        MailContentGui.setContentConfig(
            content.getString("gui.img"),
            content.getInt("gui.x"),
            content.getInt("gui.y"),
            content.getInt("gui.w"),
            content.getInt("gui.h"),
            content.getInt("gui.ww"),
            content.getInt("gui.hh"),
            content.getString("button.return.id"),
            content.getString("button.return.text"),
            content.getStringList("button.return.hover"),
            content.getString("button.return.img_1"),
            content.getString("button.return.img_2"),
            content.getInt("button.return.x"),
            content.getInt("button.return.y"),
            content.getInt("button.return.w"),
            content.getInt("button.return.h"),
            content.getString("button.collect.id"),
            content.getString("button.collect.collect.text"),
            content.getStringList("button.collect.collect.hover"),
            content.getString("button.collect.collect.img_1"),
            content.getString("button.collect.collect.img_2"),
            content.getString("button.collected.collected.text"),
            content.getStringList("button.collected.collected.hover"),
            content.getString("button.collected.collected.img_1"),
            content.getString("button.collected.collected.img_2"),
            content.getInt("button.collect.x"),
            content.getInt("button.collect.y"),
            content.getInt("button.collect.w"),
            content.getInt("button.collect.h"),
            content.getString("button.delete.id"),
            content.getString("button.delete.text"),
            content.getStringList("button.delete.hover"),
            content.getString("button.delete.img_1"),
            content.getString("button.delete.img_2"),
            content.getInt("button.delete.x"),
            content.getInt("button.delete.y"),
            content.getInt("button.delete.w"),
            content.getInt("button.delete.h"),
            content.getString("button.send.id"),
            content.getString("button.send.text"),
            content.getString("button.send.cdk"),
            content.getStringList("button.send.hover"),
            content.getString("button.send.img_1"),
            content.getString("button.send.img_2"),
            content.getInt("button.send.x"),
            content.getInt("button.send.y"),
            content.getInt("button.send.w"),
            content.getInt("button.send.h"),
            content.getInt("text.topic.x"),
            content.getInt("text.topic.y"),
            content.getDouble("text.topic.size"),
            content.getInt("text.topic.w"),
            content.getInt("text.date.x"),
            content.getInt("text.date.y"),
            content.getDouble("text.date.size"),
            content.getString("text.date.prefix"),
            content.getStringList("text.date.display"),
            content.getInt("text.deadline.x"),
            content.getInt("text.deadline.y"),
            content.getDouble("text.deadline.size"),
            content.getString("text.deadline.prefix"),
            content.getInt("text.times.x"),
            content.getInt("text.times.y"),
            content.getDouble("text.times.size"),
            content.getString("text.times.prefix"),
            content.getInt("text.key.x"),
            content.getInt("text.key.y"),
            content.getDouble("text.key.size"),
            content.getString("text.key.prefix"),
            content.getInt("text.sender.x"),
            content.getInt("text.sender.y"),
            content.getDouble("text.sender.size"),
            content.getString("text.sender.prefix"),
            content.getInt("text.coin.x"),
            content.getInt("text.coin.y"),
            content.getDouble("text.coin.size"),
            content.getString("text.coin.prefix"),
            content.getString("text.coin.suffix"),
            content.getInt("text.point.x"),
            content.getInt("text.point.y"),
            content.getDouble("text.point.size"),
            content.getString("text.point.prefix"),
            content.getString("text.point.suffix"),
            content.getInt("text.file.x"),
            content.getInt("text.file.y"),
            content.getString("text.file.text_yes"),
            content.getString("text.file.text_no"),
            content.getDouble("text.file.size"),
            content.getInt("text.cmd.x"),
            content.getInt("text.cmd.y"),
            content.getString("text.cmd.text"),
            content.getDouble("text.cmd.size"),
            content.getInt("text.content.x"),
            content.getInt("text.content.y"),
            content.getInt("text.content.w"),
            content.getInt("text.content.h"),
            content.getInt("text.content.mh"),
            content.getDouble("text.content.size"),
            content.getInt("text.content.count"),
            content.getInt("text.content.line"),
            content.getInt("text.content.sh"),
            content.getString("image.cmd.url"),
            content.getInt("image.cmd.x"),
            content.getInt("image.cmd.y"),
            content.getInt("image.cmd.w"),
            content.getInt("image.cmd.h"),
            content.getString("image.coin.url"),
            content.getInt("image.coin.x"),
            content.getInt("image.coin.y"),
            content.getInt("image.coin.w"),
            content.getInt("image.coin.h"),
            content.getString("image.point.url"),
            content.getInt("image.point.x"),
            content.getInt("image.point.y"),
            content.getInt("image.point.w"),
            content.getInt("image.point.h"),
            content.getString("slot.img"),
            content.getInt("slot.w"),
            content.getInt("slot.h"),
            content.getIntegerList("slot.x"),
            content.getIntegerList("slot.y")
        );
        // 配置SelectGui
        MailSelectGui.setSelectConfig(
            select.getString("gui.img"),
            select.getInt("gui.x"),
            select.getInt("gui.y"),
            select.getInt("gui.w"),
            select.getInt("gui.h"),
            select.getInt("gui.ww"),
            select.getInt("gui.hh"),
            select.getString("button.id.system"),
            select.getString("button.id.player"),
            select.getString("button.id.permission"),
            select.getString("button.id.date"),
            select.getString("button.id.times"),
            select.getString("button.id.keytimes"),
            select.getString("button.id.cdkey"),
            select.getString("button.id.online"),
            select.getString("button.id.template"),
            select.getString("button.img_1"),
            select.getString("button.img_2"),
            select.getIntegerList("button.x"),
            select.getIntegerList("button.y"),
            select.getInt("button.w"),
            select.getInt("button.h"),
            select.getStringList("button.list")
        );
        // 配置SendGui
        MailSendGui.setSendConfig(
            send.getString("gui.img"),
            send.getInt("gui.x"),
            send.getInt("gui.y"),
            send.getInt("gui.w"),
            send.getInt("gui.h"),
            send.getInt("gui.ww"),
            send.getInt("gui.hh"),
            send.getInt("gui.ix"),
            send.getInt("gui.iy"),
            send.getString("button.return.id"),
            send.getString("button.return.text"),
            send.getStringList("button.return.hover"),
            send.getString("button.return.img_1"),
            send.getString("button.return.img_2"),
            send.getInt("button.return.x"),
            send.getInt("button.return.y"),
            send.getInt("button.return.w"),
            send.getInt("button.return.h"),
            send.getString("button.preview.id"),
            send.getString("button.preview.text"),
            send.getStringList("button.preview.hover"),
            send.getString("button.preview.img_1"),
            send.getString("button.preview.img_2"),
            send.getInt("button.preview.x"),
            send.getInt("button.preview.y"),
            send.getInt("button.preview.w"),
            send.getInt("button.preview.h"),
            send.getString("button.preview.error"),
            send.getString("button.preview.item-ban"),
            send.getInt("text.topic.x"),
            send.getInt("text.topic.y"),
            send.getDouble("text.topic.size"),
            send.getString("text.topic.text"),
            send.getInt("text.recipient.x"),
            send.getInt("text.recipient.y"),
            send.getDouble("text.recipient.size"),
            send.getString("text.recipient.text"),
            send.getInt("text.permission.x"),
            send.getInt("text.permission.y"),
            send.getDouble("text.permission.size"),
            send.getString("text.permission.text"),
            send.getInt("text.startdate.x"),
            send.getInt("text.startdate.y"),
            send.getDouble("text.startdate.size"),
            send.getString("text.startdate.text"),
            send.getInt("text.deadline.x"),
            send.getInt("text.deadline.y"),
            send.getDouble("text.deadline.size"),
            send.getString("text.deadline.text"),
            send.getInt("text.times.x"),
            send.getInt("text.times.y"),
            send.getDouble("text.times.size"),
            send.getString("text.times.text"),
            send.getInt("text.key.x"),
            send.getInt("text.key.y"),
            send.getDouble("text.key.size"),
            send.getString("text.key.text"),
            send.getInt("text.onlyCDK.x"),
            send.getInt("text.onlyCDK.y"),
            send.getDouble("text.onlyCDK.size"),
            send.getString("text.onlyCDK.text"),
            send.getInt("text.template.x"),
            send.getInt("text.template.y"),
            send.getDouble("text.template.size"),
            send.getString("text.template.text"),
            send.getInt("text.text.x"),
            send.getInt("text.text.y"),
            send.getDouble("text.text.size"),
            send.getString("text.text.text"),
            send.getInt("text.sender.x"),
            send.getInt("text.sender.y"),
            send.getDouble("text.sender.size"),
            send.getString("text.sender.text"),
            send.getInt("text.command.x"),
            send.getInt("text.command.y"),
            send.getDouble("text.command.size"),
            send.getString("text.command.text"),
            send.getInt("text.description.x"),
            send.getInt("text.description.y"),
            send.getDouble("text.description.size"),
            send.getString("text.description.text"),
            send.getInt("text.item.x"),
            send.getInt("text.item.y"),
            send.getDouble("text.item.size"),
            send.getString("text.item.text"),
            send.getInt("field.topic.x"),
            send.getInt("field.topic.y"),
            send.getInt("field.topic.w"),
            send.getInt("field.topic.h"),
            send.getInt("field.topic.max"),
            send.getInt("field.recipient.x"),
            send.getInt("field.recipient.y"),
            send.getInt("field.recipient.w"),
            send.getInt("field.recipient.h"),
            send.getInt("field.recipient.max"),
            send.getInt("field.permission.x"),
            send.getInt("field.permission.y"),
            send.getInt("field.permission.w"),
            send.getInt("field.permission.h"),
            send.getInt("field.permission.max"),
            send.getInt("field.startdate.x"),
            send.getInt("field.startdate.y"),
            send.getInt("field.startdate.w"),
            send.getInt("field.startdate.h"),
            send.getInt("field.startdate.max"),
            send.getInt("field.deadline.x"),
            send.getInt("field.deadline.y"),
            send.getInt("field.deadline.w"),
            send.getInt("field.deadline.h"),
            send.getInt("field.deadline.max"),
            send.getInt("field.times.x"),
            send.getInt("field.times.y"),
            send.getInt("field.times.w"),
            send.getInt("field.times.h"),
            send.getInt("field.times.max"),
            send.getInt("field.key.x"),
            send.getInt("field.key.y"),
            send.getInt("field.key.w"),
            send.getInt("field.key.h"),
            send.getInt("field.key.max"),
            send.getInt("field.template.x"),
            send.getInt("field.template.y"),
            send.getInt("field.template.w"),
            send.getInt("field.template.h"),
            send.getInt("field.template.max"),
            send.getInt("field.text.x"),
            send.getInt("field.text.y"),
            send.getInt("field.text.w"),
            send.getInt("field.text.h"),
            send.getInt("field.text.max"),
            send.getInt("field.sender.x"),
            send.getInt("field.sender.y"),
            send.getInt("field.sender.w"),
            send.getInt("field.sender.h"),
            send.getInt("field.sender.max"),
            send.getInt("field.command.x"),
            send.getInt("field.command.y"),
            send.getInt("field.command.w"),
            send.getInt("field.command.h"),
            send.getInt("field.command.max"),
            send.getInt("field.description.x"),
            send.getInt("field.description.y"),
            send.getInt("field.description.w"),
            send.getInt("field.description.h"),
            send.getInt("field.description.max"),
            send.getInt("field.coin.x"),
            send.getInt("field.coin.y"),
            send.getInt("field.coin.w"),
            send.getInt("field.coin.h"),
            send.getInt("field.coin.max"),
            send.getInt("field.point.x"),
            send.getInt("field.point.y"),
            send.getInt("field.point.w"),
            send.getInt("field.point.h"),
            send.getInt("field.point.max"),
            send.getInt("checkBox.onlyCDK.x"),
            send.getInt("checkBox.onlyCDK.y"),
            send.getInt("checkBox.onlyCDK.w"),
            send.getInt("checkBox.onlyCDK.h"),
            send.getString("checkBox.onlyCDK.image1"),
            send.getString("checkBox.onlyCDK.image2"),
            send.getString("image.coin.url"),
            send.getInt("image.coin.x"),
            send.getInt("image.coin.y"),
            send.getInt("image.coin.w"),
            send.getInt("image.coin.h"),
            send.getString("image.point.url"),
            send.getInt("image.point.x"),
            send.getInt("image.point.y"),
            send.getInt("image.point.w"),
            send.getInt("image.point.h"),
            send.getString("slot.img"),
            send.getInt("slot.w"),
            send.getInt("slot.h"),
            send.getIntegerList("slot.x"),
            send.getIntegerList("slot.y")
        );
        // 配置物品修改GUI
        MailItemModifyGui.setItemModifyConfig(
            item_modify.getString("gui.img"),
            item_modify.getInt("gui.x"),
            item_modify.getInt("gui.y"),
            item_modify.getInt("gui.w"),
            item_modify.getInt("gui.h"),
            item_modify.getInt("gui.ww"),
            item_modify.getInt("gui.hh"),
            item_modify.getString("button.confirm.id"),
            item_modify.getString("button.confirm.text"),
            item_modify.getString("button.confirm.img_1"),
            item_modify.getString("button.confirm.img_2"),
            item_modify.getInt("button.confirm.x"),
            item_modify.getInt("button.confirm.y"),
            item_modify.getInt("button.confirm.w"),
            item_modify.getInt("button.confirm.h"),
            item_modify.getString("button.name.id"),
            item_modify.getString("button.name.text"),
            item_modify.getString("button.name.img_1"),
            item_modify.getString("button.name.img_2"),
            item_modify.getInt("button.name.x"),
            item_modify.getInt("button.name.y"),
            item_modify.getInt("button.name.w"),
            item_modify.getInt("button.name.h"),
            item_modify.getString("button.export.id"),
            item_modify.getString("button.export.text"),
            item_modify.getString("button.export.img_1"),
            item_modify.getString("button.export.img_2"),
            item_modify.getInt("button.export.x"),
            item_modify.getInt("button.export.y"),
            item_modify.getInt("button.export.w"),
            item_modify.getInt("button.export.h"),
            item_modify.getString("button.import.id"),
            item_modify.getString("button.import.text"),
            item_modify.getString("button.import.img_1"),
            item_modify.getString("button.import.img_2"),
            item_modify.getInt("button.import.x"),
            item_modify.getInt("button.import.y"),
            item_modify.getInt("button.import.w"),
            item_modify.getInt("button.import.h"),
            item_modify.getString("button.list.id"),
            item_modify.getString("button.list.text"),
            item_modify.getString("button.list.img_1"),
            item_modify.getString("button.list.img_2"),
            item_modify.getInt("button.list.x"),
            item_modify.getInt("button.list.y"),
            item_modify.getInt("button.list.w"),
            item_modify.getInt("button.list.h"),
            item_modify.getString("button.close.id"),
            item_modify.getString("button.close.text"),
            item_modify.getString("button.close.img_1"),
            item_modify.getString("button.close.img_2"),
            item_modify.getInt("button.close.x"),
            item_modify.getInt("button.close.y"),
            item_modify.getInt("button.close.w"),
            item_modify.getInt("button.close.h"),
            item_modify.getString("slot.img"),
            item_modify.getInt("slot.w"),
            item_modify.getInt("slot.h"),
            item_modify.getInt("slot.x"),
            item_modify.getInt("slot.y"),
            item_modify.getString("field.text.name"),
            item_modify.getString("field.text.lore"),
            item_modify.getString("field.text.export"),
            item_modify.getString("field.text.import"),
            item_modify.getInt("field.x"),
            item_modify.getInt("field.y"),
            item_modify.getInt("field.w"),
            item_modify.getInt("field.h"),
            item_modify.getInt("list.x"),
            item_modify.getInt("list.y"),
            item_modify.getInt("list.w"),
            item_modify.getInt("list.h"),
            item_modify.getInt("list.mh"),
            item_modify.getInt("list.sh"),
            item_modify.getInt("list.oh"),
            item_modify.getInt("lore.oy"),
            item_modify.getInt("lore.text.x"),
            item_modify.getInt("lore.text.fy"),
            item_modify.getDouble("lore.text.size"),
            item_modify.getString("lore.button.add.id"),
            item_modify.getString("lore.button.add.text"),
            item_modify.getStringList("lore.button.add.hover"),
            item_modify.getString("lore.button.add.img_1"),
            item_modify.getString("lore.button.add.img_2"),
            item_modify.getInt("lore.button.add.x"),
            item_modify.getInt("lore.button.add.fy"),
            item_modify.getInt("lore.button.add.w"),
            item_modify.getInt("lore.button.add.h"),
            item_modify.getString("lore.button.change.id"),
            item_modify.getString("lore.button.change.text"),
            item_modify.getStringList("lore.button.change.hover"),
            item_modify.getString("lore.button.change.img_1"),
            item_modify.getString("lore.button.change.img_2"),
            item_modify.getInt("lore.button.change.x"),
            item_modify.getInt("lore.button.change.fy"),
            item_modify.getInt("lore.button.change.w"),
            item_modify.getInt("lore.button.change.h"),
            item_modify.getString("lore.button.delete.id"),
            item_modify.getString("lore.button.delete.text"),
            item_modify.getStringList("lore.button.delete.hover"),
            item_modify.getString("lore.button.delete.img_1"),
            item_modify.getString("lore.button.delete.img_2"),
            item_modify.getInt("lore.button.delete.x"),
            item_modify.getInt("lore.button.delete.fy"),
            item_modify.getInt("lore.button.delete.w"),
            item_modify.getInt("lore.button.delete.h")
        );
        // 配置物品列表GUI
        MailItemListGui.setItemListConfig(
            item_list.getString("gui.img"),
            item_list.getInt("gui.x"),
            item_list.getInt("gui.y"),
            item_list.getInt("gui.w"),
            item_list.getInt("gui.h"),
            item_list.getInt("gui.ww"),
            item_list.getInt("gui.hh"),
            item_list.getInt("list.x"),
            item_list.getInt("list.y"),
            item_list.getInt("list.w"),
            item_list.getInt("list.h"),
            item_list.getInt("list.mh"),
            item_list.getInt("list.sh"),
            item_list.getInt("list.oh"),
            item_list.getString("slot.img"),
            item_list.getInt("slot.w"),
            item_list.getInt("slot.h"),
            item_list.getInt("slot.c"),
            item_list.getInt("slot.fx"),
            item_list.getInt("slot.fy"),
            item_list.getInt("slot.ox"),
            item_list.getInt("slot.oy")
        );
        // 配置CdkeyGUI
        MailCdkeyGUI.setCdkeyConfig(cdkey);
    }
    
    // 判断VexView文件夹是否存在
    private void ConfigExist(){
        File f = new File(DATA_FOLDER);
        if(!f.exists()){
            Bukkit.getConsoleSender().sendMessage(ConfigMessage.folder_create.replace("%folder%", "VexView"));
            f.mkdir();
        }
    }
    
    // 加载配置
    private void ConfigLoad(){
        ConfigSet(
            MailBoxAPI.configGet(DATA_FOLDER, "hud.yml", JAR_FOLDER), 
            MailBoxAPI.configGet(DATA_FOLDER, "box.yml", JAR_FOLDER), 
            MailBoxAPI.configGet(DATA_FOLDER, "content.yml", JAR_FOLDER), 
            MailBoxAPI.configGet(DATA_FOLDER, "select.yml", JAR_FOLDER), 
            MailBoxAPI.configGet(DATA_FOLDER, "send.yml", JAR_FOLDER), 
            MailBoxAPI.configGet(DATA_FOLDER, "item_modify.yml", JAR_FOLDER), 
            MailBoxAPI.configGet(DATA_FOLDER, "item_list.yml", JAR_FOLDER), 
            MailBoxAPI.configGet(DATA_FOLDER, "cdkey.yml", JAR_FOLDER)
        );
    }
    
    public static void setHover(HoverTextComponent v, List<String> t){
        v.setHover(new VexHoverText(t));
    }

}
